# Generated by Django 4.2.1 on 2025-08-13 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='metadata',
        ),
    ]
