# Generated by Django 4.2.1 on 2025-08-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_event_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
