# Generated by Django 4.2.1 on 2025-08-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_event_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_channels',
            field=models.CharField(max_length=50),
        ),
    ]
