# Generated by Django 4.2.1 on 2025-08-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_userpreference_preferred_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='mail',
            field=models.CharField(default='', max_length=500),
        ),
    ]
